openapi: 3.2.0
info:
  title: Canto PIM Dimensions API
  description: Canto APIs enable seamless synchronization between the PIM + DAM and external systems that rely on accurate, up-to-date product content.
  version: v1.0.1
servers:
- url: https://{tenantSubdomain}.{region}/api/v1/pim/
  variables:
    tenantSubdomain:
      default: demo
    region:
      enum:
      - canto.com
      - canto.global
      - canto.de
      - au.canto.com
      - ca.canto.com
      default: canto.com
security:
- bearerAuth: []
tags:
- name: Dimensions
paths:
  /dimensions:
    get:
      tags:
      - Dimensions
      summary: Get Dimensions
      description: Retrieve a list of all dimensions
      operationId: get_api_v1_dimensions
      responses:
        '200':
          description: Successfully fetched Dimensions
          headers:
            page-items:
              description: Number of items per page
              schema:
                type: integer
            link:
              description: Standard link header defined in RFC 8228. Contains links for first, last, next, and prev pages with respective `rel` attributes
              schema:
                type: string
            current-page:
              description: Current page number
              schema:
                type: integer
            total-count:
              description: Total number of items
              schema:
                type: integer
            total-pages:
              description: Total number of pages
              schema:
                type: integer
          content:
            '*/*':
              schema:
                type: object
                properties:
                  dimensions:
                    type: array
                    description: Array of Dimensions
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '500':
          description: Something went wrong
          content: {}
    post:
      tags:
      - Dimensions
      summary: Create Dimension
      description: Create a new product dimension
      operationId: post_api_v1_dimensions
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Name
          multipart/form-data:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Name
        required: true
      responses:
        '201':
          description: Successfully created Dimension
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/dimension'
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '422':
          description: There was an error creating your Dimension
          content: {}
        '500':
          description: Something went wrong
          content: {}
  /dimensions/{id}:
    get:
      tags:
      - Dimensions
      summary: Get Dimension
      description: Fetch a specific dimension by ID
      operationId: get_api_v1_dimensions_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Successfully fetched Dimension
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/dimension'
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Dimension ID not found
          content: {}
        '500':
          description: Something went wrong
          content: {}
    put:
      tags:
      - Dimensions
      summary: Update Dimension
      description: Update an existing dimension
      operationId: put_api_v1_dimensions_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Name
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Name
      responses:
        '200':
          description: Successfully updated Dimension
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/dimension'
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Dimension ID not found
          content: {}
        '422':
          description: There was an error updating your Dimension
          content: {}
        '500':
          description: Something went wrong
          content: {}
    patch:
      tags:
      - Dimensions
      summary: Update Dimension
      description: Update specific fields of an existing dimension
      operationId: patch_api_v1_dimensions_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Name
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Name
      responses:
        '200':
          description: Successfully updated Dimension
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/dimension'
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Dimension ID not found
          content: {}
        '422':
          description: There was an error updating your Dimension
          content: {}
        '500':
          description: Something went wrong
          content: {}
components:
  schemas:
    dimension:
      required:
      - dimension_options
      - id
      - name
      type: object
      properties:
        id:
          type: number
          description: Dimension ID
        name:
          type: string
          description: Dimension Name
        dimension_options:
          type: array
          description: Array of this dimension's Options
          items:
            type: string
      additionalProperties: false
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: AccessToken
x-original-swagger-version: '2.0'
