openapi: 3.2.0
info:
  title: Canto PIM Filter API
  description: Canto APIs enable seamless synchronization between the PIM + DAM and external systems that rely on accurate, up-to-date product content.
  version: v1.0.1
servers:
- url: https://{tenantSubdomain}.{region}/api/v1/pim/
  variables:
    tenantSubdomain:
      default: demo
    region:
      enum:
      - canto.com
      - canto.global
      - canto.de
      - au.canto.com
      - ca.canto.com
      default: canto.com
security:
- bearerAuth: []
tags:
- name: Filter
  description: 'API endpoints for filtering product attributes.

    Allows filtering and retrieving product attributes based on various criteria including:

    - Exact value matches

    - Partial text matches

    - Multiple value matches

    - Negative matches

    - Product type filtering

    - Product channel template filtering'
paths:
  /product_attributes/filter:
    post:
      tags:
      - Filter
      summary: Filtering product attributes
      description: Apply filters to queries based on select Product Attributes
      operationId: post_api_v1_product_attributes_filter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filter[product_type_ids]:
                  type: array
                  description: Filter by product type IDs
                  items:
                    type: string
                filter[product_channel_template_ids]:
                  type: array
                  description: Filter by product channel template IDs
                  items:
                    type: string
                filter[has_variants]:
                  type: boolean
                  description: Filter products by variant status
          multipart/form-data:
            schema:
              type: object
              properties:
                filter[product_type_ids]:
                  type: array
                  description: Filter by product type IDs
                  items:
                    type: string
                filter[product_channel_template_ids]:
                  type: array
                  description: Filter by product channel template IDs
                  items:
                    type: string
                filter[has_variants]:
                  type: boolean
                  description: Filter products by variant status
      responses:
        '200':
          description: ok
          content: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: AccessToken
x-original-swagger-version: '2.0'
