openapi: 3.2.0
info:
  title: Canto PIM Options API
  description: Canto APIs enable seamless synchronization between the PIM + DAM and external systems that rely on accurate, up-to-date product content.
  version: v1.0.1
servers:
- url: https://{tenantSubdomain}.{region}/api/v1/pim/
  variables:
    tenantSubdomain:
      default: demo
    region:
      enum:
      - canto.com
      - canto.global
      - canto.de
      - au.canto.com
      - ca.canto.com
      default: canto.com
security:
- bearerAuth: []
tags:
- name: Options
paths:
  /dimensions/{dimension_id}/options/{id}:
    put:
      tags:
      - Options
      summary: Update Dimension Option
      description: Update the value of an option within a dimension
      operationId: put_api_v1_dimensions_dimension_id_options_id
      parameters:
      - name: dimension_id
        in: path
        required: true
        schema:
          type: number
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Option Name
                position:
                  type: string
                  description: Dimension Option Position
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Option Name
                position:
                  type: string
                  description: Dimension Option Position
      responses:
        '200':
          description: Successfully updated Dimension Option
          content:
            '*/*':
              schema:
                required:
                - id
                type: object
                properties:
                  id:
                    type: number
                    description: Dimension Option ID
                  name:
                    type: string
                    description: Dimension Option Name
                  position:
                    type: string
                    description: Dimension Option Position
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Dimension or Option ID not found
          content: {}
        '422':
          description: There was an error updating your Dimension Option
          content: {}
        '500':
          description: Something went wrong
          content: {}
    patch:
      tags:
      - Options
      summary: Update Dimension Option
      description: Update the value of an option within a dimension
      operationId: patch_api_v1_dimensions_dimension_id_options_id
      parameters:
      - name: dimension_id
        in: path
        required: true
        schema:
          type: number
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Option Name
                position:
                  type: string
                  description: Dimension Option Position
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Option Name
                position:
                  type: string
                  description: Dimension Option Position
      responses:
        '200':
          description: Successfully updated Dimension Option
          content:
            '*/*':
              schema:
                required:
                - id
                type: object
                properties:
                  id:
                    type: number
                    description: Dimension Option ID
                  name:
                    type: string
                    description: Dimension Option Name
                  position:
                    type: string
                    description: Dimension Option Position
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Dimension or Option ID not found
          content: {}
        '422':
          description: There was an error updating your Dimension Option
          content: {}
        '500':
          description: Something went wrong
          content: {}
  /dimensions/{dimension_id}/options:
    post:
      tags:
      - Options
      summary: Create Dimension Option
      description: Add a new option to a dimension
      operationId: post_api_v1_dimensions_dimension_id_options
      parameters:
      - name: dimension_id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Option Name
                position:
                  type: string
                  description: Dimension Option Position
          multipart/form-data:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Dimension Option Name
                position:
                  type: string
                  description: Dimension Option Position
        required: true
      responses:
        '200':
          description: Successfully created Dimension Option
          content:
            '*/*':
              schema:
                required:
                - id
                - name
                type: object
                properties:
                  id:
                    type: number
                    description: Dimension Option ID
                  name:
                    type: string
                    description: Dimension Option Name
                  position:
                    type: string
                    description: Dimension Option Position
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '422':
          description: There was an error creating your Dimension Option
          content: {}
        '500':
          description: Something went wrong
          content: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: AccessToken
x-original-swagger-version: '2.0'
