openapi: 3.0.1
info:
  title: Canto PIM bulk_products_catalogs product_types API
  description: "\n[Canto APIs](https://api.canto.com) enable seamless synchronization between the PIM + DAM and external systems that rely on accurate, up-to-date product content. \nThe API outlined here provides programmatic access to Canto’s Product Hub (PIM).  The Product Hub API allows authorized systems to create, retrieve, update, and manage rich product data for use across digital channels, e-commerce platforms, and other target or source systems. \n \n<b>Key Capabilities</b><br />\nThe Canto Product Hub API enables full product data management:\n1. Product Record Management:  Create, read, update, and delete product entries including structured metadata, taxonomy, categories, and references.\n2. Attribute & Schema Configuration:  Access and manage custom product attributes and classification structures\n3. Webhooks:  Trigger updates or publish product datasets to downstream systems and integration pipelines.\n \n<b>API Design</b>\n- The PIM API adheres to <b>RESTful principles</b>, supporting standard HTTP methods (GET, POST, PUT, PATCH, DELETE).\n- JSON is the default payload format for both requests and responses.\n\n<b>HTTP Status Code Conventions</b><br />\nBelow are general HTTP codes applicable across most endpoints:<br />\n- <b>200, 201, 204</b> – Successful operations (retrieval, creation, update, deletion).\n- <b>400</b> – Bad request. Input payloads did not conform to the expected schema or required parameters were missing.\n- <b>401 / 403</b> – Authentication or authorization failed.\n- <b>404</b> – The route or resource was not found.\n- <b>409</b> – Conflict in resource state (e.g., duplicate product identifier).\n- <b>429</b> - Too many requests. See Rate Limits below.\n- <b>500</b> – An unexpected server error occurred.\n- <b>502 / 503 / 504</b> – Infrastructure issues such as load balancer, service unavailability, or timeouts.\n\n<b>API Rate Limits</b><br />\nRate limits are how many API calls you can make in a given time frame. If your call exceeds the pre-defined rate limit, you will run into a “429” http error-code. After which, you will need to wait until you can make another API call.\n\n<b>PIM API Rate Limit:</b> 5 requests/second\n"
  version: v1.0.1
servers:
- url: https://{tenantSubdomain}.{region}/api/v1/pim/
  variables:
    tenantSubdomain:
      default: demo
    region:
      enum:
      - canto.com
      - canto.global
      - canto.de
      - au.canto.com
      - ca.canto.com
      default: canto.com
security:
- bearerAuth: []
tags:
- name: product_types
paths:
  /product_types:
    get:
      tags:
      - product_types
      summary: Get Types
      description: '    Retrieve all available product Types

        '
      operationId: get_api_v1_product_types
      responses:
        '200':
          description: Successfully fetched Types
          headers:
            page-items:
              description: Number of items per page
              schema:
                type: integer
            link:
              description: Standard link header defined in RFC 8228. Contains links for first, last, next, and prev pages with respective `rel` attributes
              schema:
                type: string
            current-page:
              description: Current page number
              schema:
                type: integer
            total-count:
              description: Total number of items
              schema:
                type: integer
            total-pages:
              description: Total number of pages
              schema:
                type: integer
          content:
            '*/*':
              schema:
                type: object
                properties:
                  product_types:
                    type: array
                    description: Array of Product Types
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '500':
          description: Something went wrong
          content: {}
    post:
      tags:
      - product_types
      summary: Create Type
      description: '    Create a new Product Type

        '
      operationId: post_api_v1_product_types
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
          multipart/form-data:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
        required: true
      responses:
        '201':
          description: Successfully created Type
          content:
            '*/*':
              schema:
                required:
                - id
                - name
                - product_custom_attributes
                type: object
                properties:
                  id:
                    type: number
                    description: Product Type ID
                  name:
                    type: string
                    description: Product Type Name
                  product_custom_attributes:
                    type: array
                    description: Array of Non-Image Custom Attributes associated with this Type
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '422':
          description: There was an error creating your Type
          content: {}
        '500':
          description: Something went wrong
          content: {}
  /product_types/{id}:
    get:
      tags:
      - product_types
      summary: Get Type
      description: '    Get details about a specific product Type

        '
      operationId: get_api_v1_product_types_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Successfully fetched Type
          content:
            '*/*':
              schema:
                required:
                - id
                - product_custom_attributes
                type: object
                properties:
                  id:
                    type: number
                    description: Product Type ID
                  name:
                    type: string
                    description: Product Type Name
                  product_custom_attributes:
                    type: array
                    description: Array of Non-Image Custom Attributes associated with this Type
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Product Type ID not found
          content: {}
        '500':
          description: Something went wrong
          content: {}
    put:
      tags:
      - product_types
      summary: Update Type
      description: '    Fully update a product Type

        '
      operationId: put_api_v1_product_types_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
      responses:
        '200':
          description: Successfully updated Type
          content:
            '*/*':
              schema:
                required:
                - id
                - product_custom_attributes
                type: object
                properties:
                  id:
                    type: number
                    description: Product Type ID
                  name:
                    type: string
                    description: Product Type Name
                  product_custom_attributes:
                    type: array
                    description: Array of Non-Image Custom Attributes associated with this Type
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Product Type ID not found
          content: {}
        '422':
          description: There was an error updating your Type
          content: {}
        '500':
          description: Something went wrong
          content: {}
    patch:
      tags:
      - product_types
      summary: Update Type
      description: '    Patch a product Type

        '
      operationId: patch_api_v1_product_types_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
      responses:
        '200':
          description: Successfully updated Type
          content:
            '*/*':
              schema:
                required:
                - id
                - product_custom_attributes
                type: object
                properties:
                  id:
                    type: number
                    description: Product Type ID
                  name:
                    type: string
                    description: Product Type Name
                  product_custom_attributes:
                    type: array
                    description: Array of Non-Image Custom Attributes associated with this Type
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Product Type ID not found
          content: {}
        '422':
          description: There was an error updating your Type
          content: {}
        '500':
          description: Something went wrong
          content: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: AccessToken
x-original-swagger-version: '2.0'
