openapi: 3.2.0
info:
  title: Canto PIM Product Types API
  description: Canto APIs enable seamless synchronization between the PIM + DAM and external systems that rely on accurate, up-to-date product content.
  version: v1.0.1
servers:
- url: https://{tenantSubdomain}.{region}/api/v1/pim/
  variables:
    tenantSubdomain:
      default: demo
    region:
      enum:
      - canto.com
      - canto.global
      - canto.de
      - au.canto.com
      - ca.canto.com
      default: canto.com
security:
- bearerAuth: []
tags:
- name: Product Types
paths:
  /product_types:
    get:
      tags:
      - Product Types
      summary: Get Types
      description: Retrieve all available product Types
      operationId: get_api_v1_product_types
      responses:
        '200':
          description: Successfully fetched Types
          headers:
            page-items:
              description: Number of items per page
              schema:
                type: integer
            link:
              description: Standard link header defined in RFC 8228. Contains links for first, last, next, and prev pages with respective `rel` attributes
              schema:
                type: string
            current-page:
              description: Current page number
              schema:
                type: integer
            total-count:
              description: Total number of items
              schema:
                type: integer
            total-pages:
              description: Total number of pages
              schema:
                type: integer
          content:
            '*/*':
              schema:
                type: object
                properties:
                  product_types:
                    type: array
                    description: Array of Product Types
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '500':
          description: Something went wrong
          content: {}
    post:
      tags:
      - Product Types
      summary: Create Type
      description: Create a new Product Type
      operationId: post_api_v1_product_types
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
          multipart/form-data:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
        required: true
      responses:
        '201':
          description: Successfully created Type
          content:
            '*/*':
              schema:
                required:
                - id
                - name
                - product_custom_attributes
                type: object
                properties:
                  id:
                    type: number
                    description: Product Type ID
                  name:
                    type: string
                    description: Product Type Name
                  product_custom_attributes:
                    type: array
                    description: Array of Non-Image Custom Attributes associated with this Type
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '422':
          description: There was an error creating your Type
          content: {}
        '500':
          description: Something went wrong
          content: {}
  /product_types/{id}:
    get:
      tags:
      - Product Types
      summary: Get Type
      description: Get details about a specific product Type
      operationId: get_api_v1_product_types_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Successfully fetched Type
          content:
            '*/*':
              schema:
                required:
                - id
                - product_custom_attributes
                type: object
                properties:
                  id:
                    type: number
                    description: Product Type ID
                  name:
                    type: string
                    description: Product Type Name
                  product_custom_attributes:
                    type: array
                    description: Array of Non-Image Custom Attributes associated with this Type
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Product Type ID not found
          content: {}
        '500':
          description: Something went wrong
          content: {}
    put:
      tags:
      - Product Types
      summary: Update Type
      description: Fully update a product Type
      operationId: put_api_v1_product_types_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
      responses:
        '200':
          description: Successfully updated Type
          content:
            '*/*':
              schema:
                required:
                - id
                - product_custom_attributes
                type: object
                properties:
                  id:
                    type: number
                    description: Product Type ID
                  name:
                    type: string
                    description: Product Type Name
                  product_custom_attributes:
                    type: array
                    description: Array of Non-Image Custom Attributes associated with this Type
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Product Type ID not found
          content: {}
        '422':
          description: There was an error updating your Type
          content: {}
        '500':
          description: Something went wrong
          content: {}
    patch:
      tags:
      - Product Types
      summary: Update Type
      description: Patch a product Type
      operationId: patch_api_v1_product_types_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Product Type Name
      responses:
        '200':
          description: Successfully updated Type
          content:
            '*/*':
              schema:
                required:
                - id
                - product_custom_attributes
                type: object
                properties:
                  id:
                    type: number
                    description: Product Type ID
                  name:
                    type: string
                    description: Product Type Name
                  product_custom_attributes:
                    type: array
                    description: Array of Non-Image Custom Attributes associated with this Type
                    items:
                      type: string
                additionalProperties: false
        '400':
          description: The request was invalid
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '404':
          description: Product Type ID not found
          content: {}
        '422':
          description: There was an error updating your Type
          content: {}
        '500':
          description: Something went wrong
          content: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: AccessToken
x-original-swagger-version: '2.0'
