openapi: 3.2.0
info:
  title: Canto PIM Webhook Events API
  description: Canto APIs enable seamless synchronization between the PIM + DAM and external systems that rely on accurate, up-to-date product content.
  version: v1.0.1
servers:
- url: https://{tenantSubdomain}.{region}/api/v1/pim/
  variables:
    tenantSubdomain:
      default: demo
    region:
      enum:
      - canto.com
      - canto.global
      - canto.de
      - au.canto.com
      - ca.canto.com
      default: canto.com
security:
- bearerAuth: []
tags:
- name: Webhook Events
paths:
  /webhooks/{webhook_id}/events:
    get:
      tags:
      - Webhook Events
      summary: Get Webhook Events
      description: Retrieve all webhook event logs
      operationId: get_api_v1_webhooks_webhook_id_events
      parameters:
      - name: webhook_id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Successfully fetched Webhook Events
          content:
            '*/*':
              schema:
                required:
                - webhook_events
                type: object
                properties:
                  webhook_events:
                    type: array
                    description: Array of Webhook Events
                    items:
                      type: string
                additionalProperties: false
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '500':
          description: Something went wrong
          content: {}
  /webhooks/{webhook_id}/events/purge:
    delete:
      tags:
      - Webhook Events
      summary: Purge Webhook Events
      description: Clear webhook event history
      operationId: delete_api_v1_webhooks_webhook_id_events_purge
      parameters:
      - name: webhook_id
        in: path
        required: true
        schema:
          type: number
      responses:
        '204':
          description: Successfully purged all Webhook Events
          content: {}
        '401':
          description: User is not permitted to use the API or Authentication is invalid
          content: {}
        '500':
          description: Something went wrong
          content: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: AccessToken
x-original-swagger-version: '2.0'
